#!/usr/bin/env bash
# ============================================================
# Add an FSFO observer on a third host - Step 2 (run on the OBSERVER host)
# ============================================================
# Turns a bare Oracle client host into a usable FSFO observer host:
#
#   1. Pre-flight: dgmgrl / mkstore / sqlplus / tnsping present, and a
#      warning if this host is actually one of the database hosts.
#   2. Installs the two TNS entries generated by 01_prepare_primary.sh
#      into $TNS_ADMIN/tnsnames.ora (existing file backed up).
#   3. Checks raw TCP reachability of both database listeners.
#   4. Creates an auto-login Oracle Wallet holding the observer user's
#      credentials for BOTH aliases, and points sqlnet.ora at it.
#   5. Proves the whole chain: sqlplus AS SYSDG to the primary AND the
#      standby, then dgmgrl SHOW CONFIGURATION.
#
# It does not start the observer - that is 03_observer_ctl.sh.
#
# Settings come from ./observer_env.sh (written by step 1) and can be
# overridden by the flags below. Passwords are always prompted.
#
# Usage:
#   ./02_setup_observer_host.sh
#   ./02_setup_observer_host.sh -u C##DG_OBSERVER --primary-tns prim --standby-tns stby
#
# Exit codes: 0 success, 1 fatal, 2 bad arguments
#
# Note on mkstore and `ps -ef`: mkstore has no stdin-based way to pass a
# credential password to -createCredential (only the wallet password can
# be fed via heredoc), so the observer password is briefly visible on the
# argv of those two mkstore calls. One-time setup exposure, not a
# long-lived service argv.
# ============================================================

set -e
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/_lib.sh"

# Discovered settings from step 1, when the bundle is intact.
if [[ -f "${SCRIPT_DIR}/observer_env.sh" ]]; then
    source "${SCRIPT_DIR}/observer_env.sh"
    log_info "Loaded settings from ${SCRIPT_DIR}/observer_env.sh"
fi

WALLET_DIR=""
TNS_ADMIN_DIR=""
INSTALL_TNS=true

usage() {
    cat <<EOF
Usage: $(basename "$0") [options]

Prepares this host to run the Data Guard FSFO observer: TNS entries,
auto-login wallet with the SYSDG observer credentials, sqlnet.ora, and
connectivity tests against both databases.

Options:
  -u, --user USER        Observer database user (default from observer_env.sh)
      --primary-tns A    TNS alias for the primary  (default from observer_env.sh)
      --standby-tns A    TNS alias for the standby  (default from observer_env.sh)
  -w, --wallet-dir DIR   Wallet directory
                         (default: \$TNS_ADMIN/wallet, or
                          \$ORACLE_HOME/network/admin/wallet)
      --tns-admin DIR    TNS_ADMIN to configure
                         (default: \$TNS_ADMIN or \$ORACLE_HOME/network/admin)
      --no-tns           Do not touch tnsnames.ora (entries already exist)
  -h, --help             Show this help
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -u|--user)        [[ -n "${2:-}" ]] || { log_error "Missing argument for $1"; exit 2; }
                          OBSERVER_USER="$2"; shift 2 ;;
        --primary-tns)    [[ -n "${2:-}" ]] || { log_error "Missing argument for $1"; exit 2; }
                          PRIMARY_TNS_ALIAS="$2"; shift 2 ;;
        --standby-tns)    [[ -n "${2:-}" ]] || { log_error "Missing argument for $1"; exit 2; }
                          STANDBY_TNS_ALIAS="$2"; shift 2 ;;
        -w|--wallet-dir)  [[ -n "${2:-}" ]] || { log_error "Missing argument for $1"; exit 2; }
                          WALLET_DIR="$2"; shift 2 ;;
        --tns-admin)      [[ -n "${2:-}" ]] || { log_error "Missing argument for $1"; exit 2; }
                          TNS_ADMIN_DIR="$2"; shift 2 ;;
        --no-tns)         INSTALL_TNS=false; shift ;;
        -h|--help)        usage; exit 0 ;;
        *) log_error "Unknown option: $1"; usage >&2; exit 2 ;;
    esac
done

# ============================================================
# Pre-flight
# ============================================================

log_section "Pre-flight Checks"

check_oracle_env
MKSTORE="$ORACLE_HOME/bin/mkstore"
DGMGRL="$ORACLE_HOME/bin/dgmgrl"
SQLPLUS="$ORACLE_HOME/bin/sqlplus"
TNSPING="$ORACLE_HOME/bin/tnsping"

MISSING=""
[[ -x "$DGMGRL" ]]  || MISSING="${MISSING} dgmgrl"
[[ -x "$MKSTORE" ]] || MISSING="${MISSING} mkstore"
[[ -x "$SQLPLUS" ]] || MISSING="${MISSING} sqlplus"
if [[ -n "$MISSING" ]]; then
    log_error "Missing under ${ORACLE_HOME}/bin:${MISSING}"
    log_error "An FSFO observer host needs an Oracle client of the ADMINISTRATOR type"
    log_error "(or a full database home) at the same release as the databases."
    die "The Instant Client is not sufficient - it ships neither dgmgrl nor mkstore."
fi
log_info "ORACLE_HOME: ${ORACLE_HOME}"

TNS_ADMIN_DIR="${TNS_ADMIN_DIR:-${TNS_ADMIN:-$ORACLE_HOME/network/admin}}"
mkdir -p "$TNS_ADMIN_DIR"
TNSNAMES_FILE="${TNS_ADMIN_DIR}/tnsnames.ora"
SQLNET_FILE="${TNS_ADMIN_DIR}/sqlnet.ora"
log_info "TNS_ADMIN:   ${TNS_ADMIN_DIR}"

WALLET_DIR="${WALLET_DIR:-${TNS_ADMIN_DIR}/wallet}"
log_info "Wallet dir:  ${WALLET_DIR}"

if [[ -z "${OBSERVER_USER:-}" ]]; then
    prompt_with_default OBSERVER_USER "Observer database username (SYSDG)" "dg_observer"
fi
OBSERVER_USER=$(upper "$OBSERVER_USER")
[[ "$OBSERVER_USER" != "SYS" ]] \
    || die "Refusing to store SYS credentials. Create a dedicated SYSDG user with 01_prepare_primary.sh."

if [[ -z "${PRIMARY_TNS_ALIAS:-}" ]]; then
    prompt_with_default PRIMARY_TNS_ALIAS "TNS alias for the PRIMARY" ""
    [[ -n "$PRIMARY_TNS_ALIAS" ]] || die "The primary TNS alias is required."
fi
if [[ -z "${STANDBY_TNS_ALIAS:-}" ]]; then
    prompt_with_default STANDBY_TNS_ALIAS "TNS alias for the STANDBY" ""
    [[ -n "$STANDBY_TNS_ALIAS" ]] || die "The standby TNS alias is required."
fi
log_info "Aliases: primary=${PRIMARY_TNS_ALIAS} standby=${STANDBY_TNS_ALIAS} user=${OBSERVER_USER}"

# The whole point of a third host is that the observer does not share a
# failure domain with either database.
THIS_HOST=$(hostname 2>/dev/null || echo "")
THIS_SHORT="${THIS_HOST%%.*}"
for _h in "${PRIMARY_HOST:-}" "${STANDBY_HOST:-}"; do
    [[ -n "$_h" ]] || continue
    if [[ "$THIS_HOST" == "$_h" || "$THIS_SHORT" == "${_h%%.*}" ]]; then
        log_warn "This host (${THIS_HOST}) appears to be a DATABASE host (${_h})."
        log_warn "Running the observer beside a database defeats its purpose: the same"
        log_warn "outage takes out both, and FSFO cannot distinguish that from a network"
        log_warn "partition. Continue only if you know why."
        confirm_proceed "Continue anyway?" || die "Aborted - move the observer to a third host."
    fi
done

# ============================================================
# TNS entries
# ============================================================

log_section "Oracle Net Configuration"

alias_present() {
    [[ -f "$TNSNAMES_FILE" ]] || return 1
    grep -qiE "^[[:space:]]*${1}[[:space:]]*=" "$TNSNAMES_FILE"
}

if ! $INSTALL_TNS; then
    log_info "--no-tns given: leaving ${TNSNAMES_FILE} alone."
elif [[ ! -f "${SCRIPT_DIR}/tnsnames_observer.ora" ]]; then
    log_warn "tnsnames_observer.ora is not in this directory - not installing TNS entries."
    log_warn "Make sure ${TNSNAMES_FILE} already resolves both aliases."
else
    NEED_INSTALL=false
    for a in "$PRIMARY_TNS_ALIAS" "$STANDBY_TNS_ALIAS"; do
        if alias_present "$a"; then
            log_info "Alias '${a}' is already defined in ${TNSNAMES_FILE}"
        else
            NEED_INSTALL=true
        fi
    done

    if $NEED_INSTALL; then
        if [[ -f "$TNSNAMES_FILE" ]]; then
            cp "$TNSNAMES_FILE" "${TNSNAMES_FILE}.bak.$(date '+%Y%m%d_%H%M%S')"
            log_info "Backed up the existing tnsnames.ora"
        fi
        printf '\n' >> "$TNSNAMES_FILE"
        cat "${SCRIPT_DIR}/tnsnames_observer.ora" >> "$TNSNAMES_FILE"
        log_info "Appended the observer TNS entries to ${TNSNAMES_FILE}"
    fi

    # A default domain silently gets appended to every unqualified alias,
    # which would make the entries just written unresolvable.
    if [[ -f "$SQLNET_FILE" ]] && grep -qiE '^[[:space:]]*NAMES\.DEFAULT_DOMAIN' "$SQLNET_FILE"; then
        DEF_DOMAIN=$(grep -iE '^[[:space:]]*NAMES\.DEFAULT_DOMAIN' "$SQLNET_FILE" | head -1 | sed 's/.*=[[:space:]]*//' | tr -d ' \r')
        log_warn "sqlnet.ora sets NAMES.DEFAULT_DOMAIN = ${DEF_DOMAIN}"
        log_warn "Unqualified aliases resolve as '<alias>.${DEF_DOMAIN}'. If tnsping fails below,"
        log_warn "either qualify the generated entries with that domain or remove the setting."
    fi
fi

# --- raw TCP reachability --------------------------------------------
tcp_check() {
    local host="$1" port="$2"
    [[ -n "$host" && -n "$port" ]] || return 0
    if command -v nc >/dev/null 2>&1; then
        if nc -z -w 5 "$host" "$port" >/dev/null 2>&1; then
            log_info "TCP ${host}:${port} reachable"
        else
            log_warn "TCP ${host}:${port} NOT reachable from this host (firewall? wrong port?)"
        fi
        return 0
    fi
    # bash's /dev/tcp, when nc is absent
    if (exec 3<>"/dev/tcp/${host}/${port}") >/dev/null 2>&1; then
        log_info "TCP ${host}:${port} reachable"
    else
        log_warn "TCP ${host}:${port} NOT reachable from this host (firewall? wrong port?)"
    fi
    return 0
}

log_info "Checking that both listeners are reachable from here..."
tcp_check "${PRIMARY_HOST:-}" "${PRIMARY_PORT:-}"
tcp_check "${STANDBY_HOST:-}" "${STANDBY_PORT:-}"

# --- tnsping ----------------------------------------------------------
if [[ -x "$TNSPING" ]]; then
    for a in "$PRIMARY_TNS_ALIAS" "$STANDBY_TNS_ALIAS"; do
        if TNSPING_OUT=$(TNS_ADMIN="$TNS_ADMIN_DIR" "$TNSPING" "$a" 2>&1) && printf '%s\n' "$TNSPING_OUT" | grep -q '^OK'; then
            log_info "tnsping ${a}: OK"
        else
            log_error "tnsping ${a} failed:"
            printf '%s\n' "$TNSPING_OUT" | grep -E 'TNS-|ORA-' | head -3 >&2
            die "Fix Oracle Net resolution before continuing (TNS_ADMIN=${TNS_ADMIN_DIR})."
        fi
    done
else
    log_warn "tnsping not found - skipping name-resolution checks."
fi

# ============================================================
# Wallet
# ============================================================

log_section "Observer Credential Wallet"

wallet_exists() { [[ -f "${WALLET_DIR}/cwallet.sso" || -f "${WALLET_DIR}/ewallet.p12" ]]; }

NEW_WALLET=true
if wallet_exists; then
    log_warn "A wallet already exists at ${WALLET_DIR}"
    if [[ ! -f "${WALLET_DIR}/ewallet.p12" ]]; then
        # Auto-login-only wallet (cwallet.sso with no ewallet.p12): mkstore
        # has no password to verify against, so its edits exit 0 while
        # producing credentials sqlplus later rejects with ORA-01017.
        log_warn "It is auto-login-ONLY (cwallet.sso without ewallet.p12); mkstore cannot"
        log_warn "reliably modify such a wallet, so it must be rebuilt."
        confirm_proceed "Back up ${WALLET_DIR} and build a fresh wallet?" \
            || die "Cannot proceed with an auto-login-only wallet."
        mv "$WALLET_DIR" "${WALLET_DIR}.bak.$(date '+%Y%m%d_%H%M%S')"
        log_info "Old wallet moved aside."
    elif confirm_proceed "Add the observer credentials to the EXISTING wallet (answer No to rebuild it)?"; then
        NEW_WALLET=false
    else
        confirm_proceed "Back up ${WALLET_DIR} and build a fresh wallet?" \
            || die "Aborted - nothing changed."
        mv "$WALLET_DIR" "${WALLET_DIR}.bak.$(date '+%Y%m%d_%H%M%S')"
        log_info "Old wallet moved aside."
    fi
fi

if $NEW_WALLET; then
    mkdir -p "$WALLET_DIR"
    chmod 700 "$WALLET_DIR"
    prompt_password WALLET_PASSWORD  "Enter a NEW wallet password (protects the wallet file itself)"
    prompt_password WALLET_PASSWORD2 "Confirm wallet password"
    [[ "$WALLET_PASSWORD" == "$WALLET_PASSWORD2" ]] || die "Wallet passwords do not match."
    [[ -n "$WALLET_PASSWORD" ]] || die "Wallet password cannot be empty."
    unset WALLET_PASSWORD2

    if ! MK_OUT=$("$MKSTORE" -wrl "$WALLET_DIR" -create <<EOF 2>&1
${WALLET_PASSWORD}
${WALLET_PASSWORD}
EOF
    ); then
        printf '%s\n' "$MK_OUT" >&2
        die "Failed to create the wallet (Oracle wallet passwords have their own complexity rules)."
    fi
    # Auto-login (cwallet.sso) is what lets the unattended observer connect
    # as '/@alias' with no password anywhere on disk or in a start script.
    if ! MK_OUT=$("$MKSTORE" -wrl "$WALLET_DIR" -createSSO <<EOF 2>&1
${WALLET_PASSWORD}
EOF
    ); then
        printf '%s\n' "$MK_OUT" >&2
        die "Failed to enable auto-login (createSSO)."
    fi
    log_info "Auto-login wallet created at ${WALLET_DIR}"
else
    prompt_password WALLET_PASSWORD "Enter the existing wallet password for ${WALLET_DIR}"
fi

prompt_password OBSERVER_PASSWORD "Database password for ${OBSERVER_USER}"
[[ -n "$OBSERVER_PASSWORD" ]] || die "Password cannot be empty."

add_credential() {
    # Delete-then-create: -createCredential refuses to overwrite an alias
    # that already has an entry; the delete is a harmless no-op otherwise.
    local alias="$1" mk_out
    log_info "Storing ${OBSERVER_USER}@${alias} in the wallet..."
    "$MKSTORE" -wrl "$WALLET_DIR" -deleteCredential "$alias" <<EOF >/dev/null 2>&1 || true
${WALLET_PASSWORD}
EOF
    if ! mk_out=$("$MKSTORE" -wrl "$WALLET_DIR" -createCredential "$alias" "$OBSERVER_USER" "$OBSERVER_PASSWORD" <<EOF 2>&1
${WALLET_PASSWORD}
EOF
    ); then
        printf '%s\n' "$mk_out" >&2
        die "Failed to add the credential for ${alias}."
    fi
}

add_credential "$PRIMARY_TNS_ALIAS"
add_credential "$STANDBY_TNS_ALIAS"
unset OBSERVER_PASSWORD WALLET_PASSWORD
log_info "Credentials stored for both aliases."

# ============================================================
# sqlnet.ora
# ============================================================

log_section "sqlnet.ora"

WALLET_CONFIG="
# Oracle Wallet Configuration (added for the Data Guard FSFO observer)
WALLET_LOCATION = (SOURCE = (METHOD = FILE) (METHOD_DATA = (DIRECTORY = ${WALLET_DIR})))
SQLNET.WALLET_OVERRIDE = TRUE
"

if [[ -f "$SQLNET_FILE" ]]; then
    # Anchored on WALLET_LOCATION: a substring match would also hit
    # ENCRYPTION_WALLET_LOCATION, which is a TDE keystore, not a
    # credential wallet.
    if grep -Eq '^[[:space:]]*WALLET_LOCATION' "$SQLNET_FILE"; then
        log_warn "WALLET_LOCATION already present in ${SQLNET_FILE} - verify it points at ${WALLET_DIR}"
        if ! grep -Eq '^[[:space:]]*SQLNET\.WALLET_OVERRIDE[[:space:]]*=[[:space:]]*TRUE' "$SQLNET_FILE"; then
            cp "$SQLNET_FILE" "${SQLNET_FILE}.bak.$(date '+%Y%m%d_%H%M%S')"
            printf '\nSQLNET.WALLET_OVERRIDE = TRUE\n' >> "$SQLNET_FILE"
            log_info "Added the missing SQLNET.WALLET_OVERRIDE = TRUE (backup kept)."
        fi
    else
        cp "$SQLNET_FILE" "${SQLNET_FILE}.bak.$(date '+%Y%m%d_%H%M%S')"
        printf '%s\n' "$WALLET_CONFIG" >> "$SQLNET_FILE"
        log_info "Added the wallet configuration to sqlnet.ora (backup kept)."
    fi
else
    printf '%s\n' "$WALLET_CONFIG" > "$SQLNET_FILE"
    log_info "Created ${SQLNET_FILE} with the wallet configuration."
fi

# ============================================================
# Connection tests
# ============================================================

log_section "Connection Tests"

test_alias() {
    local alias="$1" expected="$2" out role
    out=$(TNS_ADMIN="$TNS_ADMIN_DIR" "$SQLPLUS" -s -L "/@${alias}" as sysdg <<EOF 2>&1 || true
set pagesize 0 heading off feedback off
select 'ROLE=' || database_role from v\$database;
exit
EOF
    )
    role=$(printf '%s\n' "$out" | sed -n 's/^ROLE=//p' | head -1 | tr -d ' \r')
    if [[ -n "$role" ]]; then
        log_info "sqlplus /@${alias} as sysdg -> connected, database_role=${role}"
        if [[ -n "$expected" && "$role" != "${expected// /}" ]]; then
            log_warn "Expected ${expected} behind '${alias}' - check the aliases (or the roles are swapped after a switchover)."
        fi
        return 0
    fi
    log_error "Connection to ${alias} as ${OBSERVER_USER} failed:"
    printf '%s\n' "$out" | grep -E 'ORA-|TNS-' | head -3 >&2
    return 1
}

PRIMARY_OK=true
STANDBY_OK=true
test_alias "$PRIMARY_TNS_ALIAS" "PRIMARY"          || PRIMARY_OK=false
test_alias "$STANDBY_TNS_ALIAS" "PHYSICAL STANDBY" || STANDBY_OK=false

if ! $PRIMARY_OK; then
    log_error "The primary connection failed. Check, in order:"
    log_error "  - the password typed above matches ${OBSERVER_USER} on the primary"
    log_error "  - the user exists with SYSDG (V\$PWFILE_USERS) - re-run 01_prepare_primary.sh"
    log_error "  - the alias resolves to the right host/port/service (tnsping ${PRIMARY_TNS_ALIAS})"
    die "Aborting: without this, there is no observer."
fi

if ! $STANDBY_OK; then
    log_error "The STANDBY connection failed while the primary works."
    log_error "That is almost always ORA-01017: the primary's password file - which now"
    log_error "carries ${OBSERVER_USER} - has not reached the standby. On 12.2+ it"
    log_error "propagates automatically while the standby receives redo; a"
    log_error "long-disconnected standby will not have it. Copy it manually:"
    log_error ""
    log_error "  primary\$ scp \$ORACLE_HOME/dbs/orapw<PRIMARY_SID> ${STANDBY_HOST:-<standby-host>}:\$ORACLE_HOME/dbs/orapw<STANDBY_SID>"
    log_error ""
    log_error "then re-run this script (it is idempotent)."
    die "Not continuing: an observer the standby rejects cannot complete a failover."
fi

log_info "Testing broker access (dgmgrl /@${PRIMARY_TNS_ALIAS})..."
DG_OUT=$(TNS_ADMIN="$TNS_ADMIN_DIR" run_dgmgrl "/@${PRIMARY_TNS_ALIAS}" "SHOW CONFIGURATION;" || true)
if printf '%s\n' "$DG_OUT" | grep -qE 'Configuration -|SUCCESS|WARNING'; then
    log_info "Broker reachable through the wallet."
    printf '%s\n' "$DG_OUT" | sed 's/^/    /'
else
    printf '%s\n' "$DG_OUT" | head -6 >&2
    die "dgmgrl could not talk to the broker with these credentials."
fi

FSFO_OUT=$(TNS_ADMIN="$TNS_ADMIN_DIR" run_dgmgrl "/@${PRIMARY_TNS_ALIAS}" "SHOW FAST_START FAILOVER;" || true)
if printf '%s\n' "$FSFO_OUT" | grep -qiE 'Fast-Start Failover:[[:space:]]*Disabled'; then
    log_warn "Fast-Start Failover is DISABLED on this configuration."
    log_warn "The observer will start and register, but it will never fail over."
    log_warn "Enable it on the primary: ./01_prepare_primary.sh --enable-fsfo"
fi

# ============================================================
# Summary
# ============================================================

cat <<EOF

============================================================
OBSERVER HOST READY
============================================================

  TNS_ADMIN     : ${TNS_ADMIN_DIR}
  Wallet        : ${WALLET_DIR}  (auto-login)
  Credentials   : ${OBSERVER_USER}@${PRIMARY_TNS_ALIAS}
                  ${OBSERVER_USER}@${STANDBY_TNS_ALIAS}
  Observer auth : dgmgrl /@${PRIMARY_TNS_ALIAS}   (no password anywhere)

If this shell's TNS_ADMIN differs from the directory above, export it in
whatever starts the observer, or the wallet and aliases will not be found:

  export TNS_ADMIN=${TNS_ADMIN_DIR}

NEXT
====
  ./03_observer_ctl.sh start
  ./04_verify_observer.sh
  ./03_observer_ctl.sh boot     # optional: restart-on-reboot

EOF
log_info "Step 2 complete."
