# ============================================================
# Shared helpers for the "add an FSFO observer on a third host" kit.
# Sourced by the numbered scripts in this directory.
#
# Deliberately standalone: no dependency on common/dg_functions.sh,
# the NFS share, or standby_config_*.env, so this folder (or the
# bundle generated by 01_prepare_primary.sh) can be copied on its
# own to the primary and to the observer host.
# ============================================================

# Colors (respect NO_COLOR and non-TTY stdout)
if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
    C_INFO=$(printf '\033[0;32m'); C_WARN=$(printf '\033[0;33m')
    C_ERR=$(printf '\033[0;31m');  C_OFF=$(printf '\033[0m')
else
    C_INFO=""; C_WARN=""; C_ERR=""; C_OFF=""
fi

log_info()  { printf '%s[INFO]%s  %s\n' "$C_INFO" "$C_OFF" "$*"; }
log_warn()  { printf '%s[WARN]%s  %s\n' "$C_WARN" "$C_OFF" "$*" >&2; }
log_error() { printf '%s[ERROR]%s %s\n' "$C_ERR" "$C_OFF" "$*" >&2; }
die()       { log_error "$*"; exit 1; }

log_section() {
    printf '\n============================================================\n'
    printf '%s\n' "$*"
    printf '============================================================\n'
}

# prompt_password VAR "Prompt text" -> sets VAR (never echoed).
# Interactive only: these scripts never accept passwords via argv or env.
prompt_password() {
    local __var="$1" __prompt="$2" __val=""
    [[ -t 0 ]] || die "A password prompt is required (${__prompt}) but stdin is not a terminal. Run interactively."
    printf '%s: ' "$__prompt" >&2
    IFS= read -rs __val
    printf '\n' >&2
    printf -v "$__var" '%s' "$__val"
}

# prompt_with_default VAR "Prompt text" "default"
# Non-TTY stdin takes the default silently.
prompt_with_default() {
    local __var="$1" __prompt="$2" __def="$3" __val=""
    if [[ -t 0 ]]; then
        printf '%s [%s]: ' "$__prompt" "$__def" >&2
        IFS= read -r __val
    fi
    [[ -n "$__val" ]] || __val="$__def"
    printf -v "$__var" '%s' "$__val"
}

# confirm_proceed "Question?" -> 0 yes / 1 no. Non-TTY: no (safe default).
confirm_proceed() {
    local ans=""
    if [[ ! -t 0 ]]; then
        log_warn "Non-interactive stdin: answering NO to: $1"
        return 1
    fi
    printf '%s [y/N]: ' "$1" >&2
    IFS= read -r ans
    case "$ans" in
        y|Y|yes|YES|Yes) return 0 ;;
        *)               return 1 ;;
    esac
}

check_oracle_env() {
    [[ -n "${ORACLE_HOME:-}" ]] || die "ORACLE_HOME is not set."
    [[ -x "$ORACLE_HOME/bin/sqlplus" || -x "$ORACLE_HOME/bin/dgmgrl" ]] \
        || die "Neither sqlplus nor dgmgrl found under $ORACLE_HOME/bin - is ORACLE_HOME correct?"
}

# ------------------------------------------------------------
# Text helpers
# ------------------------------------------------------------
clean() { tr -d ' \t\r' | sed '/^$/d'; }                    # strip ALL spaces/tabs
trim()  { tr -d '\r' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d'; }
field() { awk -F'|' -v i="$2" '{print $i}' <<< "$1"; }

upper() { printf '%s' "$1" | tr '[:lower:]' '[:upper:]'; }

# ------------------------------------------------------------
# SQL*Plus / DGMGRL wrappers
# ------------------------------------------------------------
# run_sql "sql" -> stdout. Connects '/ as sysdba' to the local instance.
# The heredoc is unquoted so callers must escape dollar signs in view
# names (v\$database) when building the SQL in double quotes.
# SET DEFINE OFF comes first: callers embed passwords (CREATE/ALTER USER ...
# IDENTIFIED BY "..."), and with substitution on, an '&' in a password is
# taken for a substitution variable and the statement silently changes.
run_sql() {
    "$ORACLE_HOME/bin/sqlplus" -s -L / as sysdba <<EOF
set define off
set pagesize 0 feedback off verify off heading off echo off trimspool on tab off linesize 32767
whenever sqlerror exit 1
$1
exit
EOF
}

# run_sql_as "<connect spec>" "sql" - e.g. run_sql_as "/@prim as sysdg" "select ..."
# The connect spec is intentionally unquoted at the call site below so
# bash splits it into sqlplus's argv ("/@prim" "as" "sysdg").
run_sql_as() {
    local __conn="$1" __sql="$2"
    # shellcheck disable=SC2086
    "$ORACLE_HOME/bin/sqlplus" -s -L $__conn <<EOF
set define off
set pagesize 0 feedback off verify off heading off echo off trimspool on tab off linesize 32767
whenever sqlerror exit 1
${__sql}
exit
EOF
}

# run_dgmgrl "<conn>" "cmd" ["cmd" ...] -> stdout+stderr merged.
# Return semantics: the status is dgmgrl's own, which -silent makes 0 even
# when a command inside failed. Unlike run_dgmgrl in common/dg_functions.sh
# and migrate_noncdb_to_pdb/_lib.sh (which fold the error scan into the
# return code), every caller here must judge the OUTPUT with dgmgrl_failed
# (or pattern-match it), never the exit status. Callers capture it as
# out=$(run_dgmgrl ... || true), so pipefail/set -e never sees it.
run_dgmgrl() {
    local __conn="$1"; shift
    printf '%s\n' "$@" | "$ORACLE_HOME/bin/dgmgrl" -silent "$__conn" 2>&1
}

# dgmgrl_failed "<output>" -> 0 when the output of a command that is expected
# to produce a result looks like a failure. Same rules as
# dgmgrl_output_has_error in common/dg_functions.sh (kept as a copy: this kit
# is standalone), plus the empty-output case:
#   - empty/whitespace-only output is a failure (dgmgrl could not start or
#     connect and printed nothing; every caller expects a reply)
#   - ORA-/DGM- codes count, except on a 'Warning:' line (a member-level
#     'Warning: ORA-16789' is a health note, not a failed command)
#   - a standalone 'Error: N' with N nonzero ('Error: 0' is a benign status)
#   - a standalone 'Failed.' line
dgmgrl_failed() {
    local __out="$1" __body
    [[ -n "$(printf '%s' "$__out" | tr -d ' \t\r\n')" ]] || return 0
    __body=$(printf '%s\n' "$__out" | grep -viE '^[[:space:]]*Warning:' || true)
    printf '%s\n' "$__body" | grep -Eq 'ORA-[0-9]|DGM-[0-9]' && return 0
    printf '%s\n' "$__body" | grep -Eiq '^[[:space:]]*Error:[[:space:]]*[1-9]' && return 0
    printf '%s\n' "$__body" | grep -Eiq '^[[:space:]]*Failed\.[[:space:]]*$' && return 0
    return 1
}

# ------------------------------------------------------------
# Broker property extraction
# ------------------------------------------------------------
# broker_property "<SHOW DATABASE VERBOSE output>" PropertyName -> value
# A missing property prints nothing and still returns 0: grep's status 1 on
# no match would otherwise abort a set -e + pipefail caller, silently, before
# any --*-host override or "re-run with ..." hint could be reached.
broker_property() {
    printf '%s\n' "$1" \
        | grep -i "^[[:space:]]*${2}[[:space:]]*=" | head -1 \
        | sed -e "s/^[^=]*=[[:space:]]*//" -e "s/^'//" -e "s/'.*\$//" -e "s/[[:space:]]*\$//" \
        || true
}

# resolve_descriptor ALIAS -> the connect descriptor tnsping resolved,
# on one line, or empty. This is the most reliable way to learn the host,
# port and service the Data Guard members already use for each other:
# it is whatever the local Oracle Net configuration actually resolves.
resolve_descriptor() {
    local __alias="$1" __out=""
    [[ -n "$__alias" ]] || return 0
    [[ -x "$ORACLE_HOME/bin/tnsping" ]] || return 0
    __out=$("$ORACLE_HOME/bin/tnsping" "$__alias" 2>/dev/null || true)
    printf '%s\n' "$__out" \
        | sed -n 's/^Attempting to contact //p' | head -1 \
        | sed -e 's/[[:space:]]*$//'
}

# descriptor_part "<descriptor>" HOST|PORT|SERVICE_NAME -> value or empty
# The key match is case-insensitive ((host = x) is as valid as (HOST = x)),
# done with [Hh][Oo][Ss][Tt] brackets because AIX sed has no I flag.
descriptor_part() {
    local __key
    __key=$(printf '%s' "$2" | awk '{ o = ""; for (i = 1; i <= length($0); i++) { c = substr($0, i, 1); u = toupper(c); l = tolower(c); o = o (u == l ? c : "[" u l "]") } print o }')
    printf '%s' "$1" | sed -n "s/.*(${__key}[[:space:]]*=[[:space:]]*\\([^)[:space:]]*\\).*/\\1/p" | head -1
}

# tns_descriptor HOST PORT SERVICE -> a formatted DESCRIPTOR block
tns_descriptor() {
    cat <<EOF
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = ${1})(PORT = ${2}))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = ${3})
    )
  )
EOF
}

# ------------------------------------------------------------
# Observer liveness (SHOW OBSERVER)
# ------------------------------------------------------------
# Being listed is not the same as running: the broker keeps a crashed
# observer registered, and only its 'Last Ping to ...' age (which keeps
# growing, or reads '(unknown)') gives it away. 19c prints one block per
# observer:
#
#   Observer "dg_observer" - Master
#
#     Host Name:                    ol9-19-dg3.localdomain
#     Last Ping to Primary:         0 seconds ago
#     Last Ping to Target:          1 second ago
#
# observer_block "<SHOW OBSERVER output>" NAME HOST -> KEY=VALUE lines for
# THIS observer's block only, so another observer's healthy ping can never
# vouch for this one. The block is the one named NAME (case-insensitive),
# else the first one whose Host Name is HOST (full or short form) - the same
# rule the kit has always used to recognise "this" observer.
#   BLOCKS=<n>                 observer blocks found; 0 = nothing parseable
#   MATCH=name|host|none
#   NAME= ROLE= HOST=          the matched block's name, Master/Backup, host
#   PING_PRIMARY= PING_TARGET= whole seconds; empty unless the value reads
#                              'N second(s) ago'
#   PING_PRIMARY_TEXT= PING_TARGET_TEXT=   the value as printed
# CRLF line endings are tolerated. POSIX awk only (no arrays at all).
observer_block() {
    local __name __host
    __name=$(printf '%s' "$2" | tr '[:upper:]' '[:lower:]')
    __host=$(printf '%s' "$3" | tr -d ' \r' | tr '[:upper:]' '[:lower:]')
    printf '%s\n' "$1" | tr -d '\r' | awk -v me_name="$__name" -v me_host="$__host" -v me_short="${__host%%.*}" '
        function val(l) { sub(/^[^:]*:[ \t]*/, "", l); sub(/[ \t]*$/, "", l); return l }
        function secs(v) {
            if (v ~ /^[0-9][0-9]* seconds? ago$/) { sub(/ .*$/, "", v); return v }
            return ""
        }
        function flush(  lh, sh) {
            if (!inblk) return
            if (!nm && me_name != "" && tolower(bname) == me_name) {
                nm = 1; n_name = bname; n_role = brole; n_host = bhost; n_pp = bpp; n_pt = bpt
            }
            if (!hm && me_host != "" && bhost != "") {
                lh = tolower(bhost); gsub(/ /, "", lh); sh = lh; sub(/\..*$/, "", sh)
                if (lh == me_host || sh == me_short) {
                    hm = 1; h_name = bname; h_role = brole; h_host = bhost; h_pp = bpp; h_pt = bpt
                }
            }
        }
        BEGIN { inblk = 0; blocks = 0; nm = 0; hm = 0 }
        /^[ \t]*Observer[ \t]*"/ {
            flush(); inblk = 1; blocks = blocks + 1
            bname = $0; sub(/^[ \t]*Observer[ \t]*"/, "", bname); sub(/".*$/, "", bname)
            brole = ""
            if ($0 ~ /-[ \t]*Master/) brole = "Master"
            if ($0 ~ /-[ \t]*Backup/) brole = "Backup"
            bhost = ""; bpp = ""; bpt = ""
            next
        }
        inblk && /^[ \t]*Host Name:/            { bhost = val($0); next }
        inblk && /^[ \t]*Last Ping to Primary:/ { bpp = val($0); next }
        inblk && /^[ \t]*Last Ping to Target:/  { bpt = val($0); next }
        END {
            flush()
            m = "none"; o_name = ""; o_role = ""; o_host = ""; o_pp = ""; o_pt = ""
            if (nm)      { m = "name"; o_name = n_name; o_role = n_role; o_host = n_host; o_pp = n_pp; o_pt = n_pt }
            else if (hm) { m = "host"; o_name = h_name; o_role = h_role; o_host = h_host; o_pp = h_pp; o_pt = h_pt }
            print "BLOCKS=" blocks
            print "MATCH=" m
            print "NAME=" o_name
            print "ROLE=" o_role
            print "HOST=" o_host
            print "PING_PRIMARY=" secs(o_pp)
            print "PING_PRIMARY_TEXT=" o_pp
            print "PING_TARGET=" secs(o_pt)
            print "PING_TARGET_TEXT=" o_pt
        }
    '
}

# obs_field "<observer_block output>" KEY -> value
obs_field() { printf '%s\n' "$1" | sed -n "s/^${2}=//p" | head -1; }

# observer_ping "<observer_block output>" primary|target|either
#   -> "<seconds>|<label>|<value as printed>"; seconds is empty when the age
#   is missing or not a number ('(unknown)'), which counts as not live.
#   'either' takes the fresher of the two pings of THIS block: for a session
#   whose member's role is not known - after a failover the standby alias is
#   the new primary, before one it is still the target.
observer_ping() {
    local __p __t __pt __tt
    __p=$(obs_field "$1" PING_PRIMARY); __pt=$(obs_field "$1" PING_PRIMARY_TEXT)
    __t=$(obs_field "$1" PING_TARGET);  __tt=$(obs_field "$1" PING_TARGET_TEXT)
    case "$2" in
        primary) printf '%s|last ping to primary|%s\n' "$__p" "${__pt:-(none)}" ;;
        target)  printf '%s|last ping to target|%s\n'  "$__t" "${__tt:-(none)}" ;;
        *)
            if [[ -n "$__t" ]] && { [[ -z "$__p" ]] || (( 10#$__t < 10#$__p )); }; then
                printf '%s|last ping to target|%s\n' "$__t" "${__tt:-(none)}"
            else
                printf '%s|last ping to primary|%s\n' "$__p" "${__pt:-(none)}"
            fi
            ;;
    esac
}

# ping_is_fresh SECONDS LIMIT -> 0 when SECONDS is a number no larger than LIMIT
ping_is_fresh() {
    [[ -n "$1" ]] || return 1
    case "$1" in *[!0-9]*) return 1 ;; esac
    (( 10#$1 <= 10#$2 ))
}

# valid_ping_age VALUE -> 0 when VALUE is a positive whole number of seconds
# (at most 9 digits, no leading zero) - the DG_OBS_MAX_PING_AGE contract.
valid_ping_age() {
    case "$1" in ''|*[!0-9]*|0*) return 1 ;; esac
    [[ ${#1} -le 9 ]]
}

# valid_db_username NAME -> 0 when it is a usable unquoted identifier
valid_db_username() {
    printf '%s' "$1" | grep -q '^[A-Za-z][A-Za-z0-9_$#]*$' && [[ ${#1} -le 30 ]]
}
