# ============================================================
# Shared helpers for the "add an FSFO observer on a third host" kit.
# Sourced by the numbered scripts in this directory.
#
# Deliberately standalone: no dependency on common/dg_functions.sh,
# the NFS share, or standby_config_*.env, so this folder (or the
# bundle generated by 01_prepare_primary.sh) can be copied on its
# own to the primary and to the observer host.
# ============================================================

# Colors (respect NO_COLOR and non-TTY stdout)
if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
    C_INFO=$(printf '\033[0;32m'); C_WARN=$(printf '\033[0;33m')
    C_ERR=$(printf '\033[0;31m');  C_OFF=$(printf '\033[0m')
else
    C_INFO=""; C_WARN=""; C_ERR=""; C_OFF=""
fi

log_info()  { printf '%s[INFO]%s  %s\n' "$C_INFO" "$C_OFF" "$*"; }
log_warn()  { printf '%s[WARN]%s  %s\n' "$C_WARN" "$C_OFF" "$*" >&2; }
log_error() { printf '%s[ERROR]%s %s\n' "$C_ERR" "$C_OFF" "$*" >&2; }
die()       { log_error "$*"; exit 1; }

log_section() {
    printf '\n============================================================\n'
    printf '%s\n' "$*"
    printf '============================================================\n'
}

# prompt_password VAR "Prompt text" -> sets VAR (never echoed).
# Interactive only: these scripts never accept passwords via argv or env.
prompt_password() {
    local __var="$1" __prompt="$2" __val=""
    [[ -t 0 ]] || die "A password prompt is required (${__prompt}) but stdin is not a terminal. Run interactively."
    printf '%s: ' "$__prompt" >&2
    IFS= read -rs __val
    printf '\n' >&2
    printf -v "$__var" '%s' "$__val"
}

# prompt_with_default VAR "Prompt text" "default"
# Non-TTY stdin takes the default silently.
prompt_with_default() {
    local __var="$1" __prompt="$2" __def="$3" __val=""
    if [[ -t 0 ]]; then
        printf '%s [%s]: ' "$__prompt" "$__def" >&2
        IFS= read -r __val
    fi
    [[ -n "$__val" ]] || __val="$__def"
    printf -v "$__var" '%s' "$__val"
}

# confirm_proceed "Question?" -> 0 yes / 1 no. Non-TTY: no (safe default).
confirm_proceed() {
    local ans=""
    if [[ ! -t 0 ]]; then
        log_warn "Non-interactive stdin: answering NO to: $1"
        return 1
    fi
    printf '%s [y/N]: ' "$1" >&2
    IFS= read -r ans
    case "$ans" in
        y|Y|yes|YES|Yes) return 0 ;;
        *)               return 1 ;;
    esac
}

check_oracle_env() {
    [[ -n "${ORACLE_HOME:-}" ]] || die "ORACLE_HOME is not set."
    [[ -x "$ORACLE_HOME/bin/sqlplus" || -x "$ORACLE_HOME/bin/dgmgrl" ]] \
        || die "Neither sqlplus nor dgmgrl found under $ORACLE_HOME/bin - is ORACLE_HOME correct?"
}

# ------------------------------------------------------------
# Text helpers
# ------------------------------------------------------------
clean() { tr -d ' \t\r' | sed '/^$/d'; }                    # strip ALL spaces/tabs
trim()  { tr -d '\r' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d'; }
field() { awk -F'|' -v i="$2" '{print $i}' <<< "$1"; }

upper() { printf '%s' "$1" | tr '[:lower:]' '[:upper:]'; }

# ------------------------------------------------------------
# SQL*Plus / DGMGRL wrappers
# ------------------------------------------------------------
# run_sql "sql" -> stdout. Connects '/ as sysdba' to the local instance.
# The heredoc is unquoted so callers must escape dollar signs in view
# names (v\$database) when building the SQL in double quotes.
run_sql() {
    "$ORACLE_HOME/bin/sqlplus" -s -L / as sysdba <<EOF
set pagesize 0 feedback off verify off heading off echo off trimspool on tab off linesize 32767
whenever sqlerror exit 1
$1
exit
EOF
}

# run_sql_as "<connect spec>" "sql" - e.g. run_sql_as "/@prim as sysdg" "select ..."
# The connect spec is intentionally unquoted at the call site below so
# bash splits it into sqlplus's argv ("/@prim" "as" "sysdg").
run_sql_as() {
    local __conn="$1" __sql="$2"
    # shellcheck disable=SC2086
    "$ORACLE_HOME/bin/sqlplus" -s -L $__conn <<EOF
set pagesize 0 feedback off verify off heading off echo off trimspool on tab off linesize 32767
whenever sqlerror exit 1
${__sql}
exit
EOF
}

# run_dgmgrl "<conn>" "cmd" ["cmd" ...] -> stdout+stderr merged.
# NOTE: dgmgrl -silent exits 0 even when a command fails, so every caller
# must judge the OUTPUT, never the exit status.
run_dgmgrl() {
    local __conn="$1"; shift
    printf '%s\n' "$@" | "$ORACLE_HOME/bin/dgmgrl" -silent "$__conn" 2>&1
}

# dgmgrl_failed "<output>" -> 0 when the output looks like a failure.
dgmgrl_failed() {
    printf '%s\n' "$1" | grep -qiE 'ORA-[0-9]|DGM-[0-9]|^Error:|Failed\.'
}

# ------------------------------------------------------------
# Broker property extraction
# ------------------------------------------------------------
# broker_property "<SHOW DATABASE VERBOSE output>" PropertyName -> value
broker_property() {
    printf '%s\n' "$1" \
        | grep -i "^[[:space:]]*${2}[[:space:]]*=" | head -1 \
        | sed -e "s/^[^=]*=[[:space:]]*//" -e "s/^'//" -e "s/'.*\$//" -e "s/[[:space:]]*\$//"
}

# resolve_descriptor ALIAS -> the connect descriptor tnsping resolved,
# on one line, or empty. This is the most reliable way to learn the host,
# port and service the Data Guard members already use for each other:
# it is whatever the local Oracle Net configuration actually resolves.
resolve_descriptor() {
    local __alias="$1" __out=""
    [[ -n "$__alias" ]] || return 0
    [[ -x "$ORACLE_HOME/bin/tnsping" ]] || return 0
    __out=$("$ORACLE_HOME/bin/tnsping" "$__alias" 2>/dev/null || true)
    printf '%s\n' "$__out" \
        | sed -n 's/^Attempting to contact //p' | head -1 \
        | sed -e 's/[[:space:]]*$//'
}

# descriptor_part "<descriptor>" HOST|PORT|SERVICE_NAME -> value or empty
descriptor_part() {
    printf '%s' "$1" | sed -n "s/.*(${2}[[:space:]]*=[[:space:]]*\\([^)[:space:]]*\\).*/\\1/p" | head -1
}

# tns_descriptor HOST PORT SERVICE -> a formatted DESCRIPTOR block
tns_descriptor() {
    cat <<EOF
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = ${1})(PORT = ${2}))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = ${3})
    )
  )
EOF
}

# valid_db_username NAME -> 0 when it is a usable unquoted identifier
valid_db_username() {
    printf '%s' "$1" | grep -q '^[A-Za-z][A-Za-z0-9_$#]*$' && [[ ${#1} -le 30 ]]
}
