-- Get count of DMON (Data Guard Broker) processes
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT COUNT(*) FROM V$PROCESS WHERE PNAME LIKE 'DMON%';
EXIT;
