-- Get MRP info as pipe-delimited string (for parsing)
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET HEADING OFF FEEDBACK OFF LINESIZE 200
SELECT PROCESS || '|' || STATUS || '|' || NVL(TO_CHAR(SEQUENCE#), 'N/A')
FROM V$MANAGED_STANDBY
WHERE PROCESS = 'MRP0';
EXIT;
