-- Get existing Data Guard Broker configuration name
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT NAME FROM V$DG_BROKER_CONFIG WHERE ROWNUM=1;
EXIT;
