-- Get redo log size in MB
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT DISTINCT BYTES/1024/1024 FROM V$LOG WHERE ROWNUM=1;
EXIT;
