-- Get archive destination configuration (with headers for display)
SET LINESIZE 200 PAGESIZE 50
COLUMN DEST_NAME FORMAT A20
COLUMN STATUS FORMAT A10
COLUMN DESTINATION FORMAT A60
SELECT DEST_ID, DEST_NAME, STATUS, TARGET, DESTINATION
FROM V$ARCHIVE_DEST
WHERE DEST_ID IN (1, 2);
EXIT;
