-- Get archive destination from existing archived logs
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT DISTINCT SUBSTR(NAME, 1, INSTR(NAME, '/', -1)-1)
FROM V$ARCHIVED_LOG WHERE NAME IS NOT NULL AND ROWNUM=1;
EXIT;
