-- Get count of UNNAMED placeholder datafiles (ORA-01274: a new datafile's
-- primary-side path was not covered by DB_FILE_NAME_CONVERT on the standby)
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT COUNT(*) FROM V$DATAFILE WHERE NAME LIKE '%UNNAMED%';
EXIT;
