-- Get maximum redo log group number (from both online and standby redo logs)
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT NVL(MAX(GROUP#), 0) FROM (SELECT GROUP# FROM V$LOG UNION SELECT GROUP# FROM V$STANDBY_LOG);
EXIT;
