-- Get archive destination path from V$ARCHIVE_DEST
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT DESTINATION FROM V$ARCHIVE_DEST
WHERE DEST_ID=1 AND STATUS='VALID' AND DESTINATION IS NOT NULL;
EXIT;
