-- Get distinct datafile directories
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT DISTINCT SUBSTR(NAME, 1, INSTR(NAME, '/', -1)-1)
FROM V$DATAFILE
ORDER BY 1;
EXIT;
