-- Get database role (PRIMARY, PHYSICAL STANDBY, etc.)
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT DATABASE_ROLE FROM V$DATABASE;
EXIT;
