-- Get listener port from V$LISTENER_NETWORK
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT VALUE FROM V$LISTENER_NETWORK WHERE TYPE='LOCAL LISTENER' AND ROWNUM=1;
EXIT;
