-- Identity of the connected database as DB_UNIQUE_NAME|DATABASE_ROLE|DBID
-- (assert_db_matches_config compares it with the selected standby_config_*.env)
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET DEFINE OFF
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT DB_UNIQUE_NAME || '|' || DATABASE_ROLE || '|' || TO_CHAR(DBID) FROM V$DATABASE;
EXIT;
