-- Get full standby redo log information (with headers for display)
SET LINESIZE 150 PAGESIZE 50
SELECT GROUP#, THREAD#, BYTES/1024/1024 AS SIZE_MB, STATUS, ARCHIVED
FROM V$STANDBY_LOG
ORDER BY GROUP#;
EXIT;
