-- Get user-defined services (excludes system services)
-- Returns one service name per line
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT NAME
FROM V$ACTIVE_SERVICES
WHERE NAME NOT IN (
    SELECT DB_UNIQUE_NAME FROM V$DATABASE
    UNION ALL
    SELECT NAME FROM V$DATABASE
    UNION ALL
    SELECT INSTANCE_NAME FROM V$INSTANCE
)
AND NAME NOT LIKE 'SYS$%'
AND UPPER(NAME) NOT LIKE '%XDB%'
ORDER BY NAME;
EXIT;
