-- Get archive log apply status (with headers for display)
SET LINESIZE 150 PAGESIZE 50
SELECT THREAD#, MAX(SEQUENCE#) AS LAST_APPLIED
FROM V$ARCHIVED_LOG
WHERE APPLIED = 'YES'
GROUP BY THREAD#;
EXIT;
