-- Get count of archive destinations with errors
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT COUNT(*) FROM V$ARCHIVE_DEST WHERE STATUS = 'ERROR' AND DEST_ID IN (1,2);
EXIT;
