-- Get database log mode (ARCHIVELOG or NOARCHIVELOG)
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT LOG_MODE FROM V$DATABASE;
EXIT;
