-- Get Managed Recovery Process status
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT PROCESS || ':' || STATUS FROM V$MANAGED_STANDBY WHERE PROCESS = 'MRP0';
EXIT;
