-- Get path of first redo log member
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT SUBSTR(MEMBER, 1, INSTR(MEMBER, '/', -1)) FROM V$LOGFILE WHERE ROWNUM=1;
EXIT;
