-- Get distinct redo log file paths
SET HEADING OFF FEEDBACK OFF VERIFY OFF LINESIZE 1000 PAGESIZE 0 TRIMSPOOL ON
SELECT DISTINCT SUBSTR(MEMBER, 1, INSTR(MEMBER, '/', -1)) AS PATH FROM V$LOGFILE;
EXIT;
